version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" 
    volumes:
      - ./arosaje.sql:/docker-entrypoint-initdb.d/arosaje.sql